name: flutter_generator
description: "Flutter Generator Pro - Custom CLI tools untuk mempercepat development Flutter dengan Clean Architecture & Riverpod."
version: 1.0.0
homepage:

environment:
  sdk: ^3.12.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0
  json_annotation: ^4.12.0
  analyzer: ^12.0.0
  path: ^1.9.1

executables:
  flutter_generator: flutter_generator
  gen_model: generate
  gen_usecase: generate_usecase
  gen_page: generate_page

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.15.1
  freezed: ^3.2.6-dev.1
  json_serializable: ^6.14.0
